---
title: "Schedule"
---

| **Week** | **Date** | **Theme**                                        |**Presentations**                           | **Assignment Assigned** | **Assignment Due**     | **Reading**                                                                                                                                                                                                                                                                                      |
| :------: | :------: | :----------------------------------------------- |:-------------------------------------------| :---------------------- | :--------------------- | :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|    1a    |  1/7/19  | [Intro to the course](slides/w1p1.html)          |                                            | Final Project           | -                      | [Bryan 4-8](http://happygitwithr.com/installation-pain.html) (9 optional)                                                                                                                                                                                                                        |
|    1b    |  1/9/19  | GitHub group project                             |                                            | Lab 1                   | -                      | [Bryan 13](http://happygitwithr.com/rstudio-git-github.html), [Bryan 16](http://happygitwithr.com/new-github-first.html) (14-15 optional)                                                                                                                                                        |
|    2a    | 1/14/19  | **Guest Lecture** Introduction to visualizations |                                            | -                       | Lab 1                  | [Healy 4 (Show the right numbers)](https://socviz.co/groupfacettx.html#groupfacettx), [R4DS 28 (Graphics for communication)](https://r4ds.had.co.nz/graphics-for-communication.html), [Wilke 5 (Directory of visualizations)](https://serialmentor.com/dataviz/directory-of-visualizations.html) |
|    2b    | 1/16/19  | **No Class** Take-home lab                       |                                            | Lab 2                   | -                      | If needed: [Healy 2 (Get started)](https://socviz.co/gettingstarted.html#gettingstarted), [Healy 3 (Make a plot)](https://socviz.co/makeplot.html#makeplot)                                                                                                                                      |
|    3a    | 1/21/19  | Joins 1                                          |                                            | -                       | Lab 2                  | [R4DS 13 (Relational data)](https://r4ds.had.co.nz/relational-data.html)                                                                                                                                                                                                                         |
|    3b    | 1/23/19  | Joins 2                                          |Jessica: [gganimate](https://gganimate.com) | Homework 1              | -                      | -                                                                                                                                                                                                                                                                                                |
|    4a    | 1/28/19  | Visual perception                                |                                            | -                       | -                      | [Healy 1 (Look at data)](https://socviz.co/lookatdata.html#lookatdata)                                                                                                                                                                                                                           |
|    4b    | 1/30/19  | Hands-on lab                                     |                                            | Lab 3                   | Homework 1             | [Wilke 2 (Visualizing data: Mapping data onto aesthetics)](https://serialmentor.com/dataviz/aesthetic-mapping.html)                                                                                                                                                                              |
|    5a    |  2/4/19  | Color                                            |                                            | -                       | Lab 3                  | [Wilke 4 (Color scales)](https://serialmentor.com/dataviz/color-basics.html), [Wilke 16 (Common pitfalls of color use)](https://serialmentor.com/dataviz/color-pitfalls.html)                                                                                                                    |
|    5b    |  2/6/19  | **No Class/Guest Lecture** Hands-on lab          |                                            | Lab 4                   | Final Project Proposal | [Wilke 6 (Visualizing amounts)](https://serialmentor.com/dataviz/visualizing-amounts.html)                                                                                                                                                                                                       |
|    6a    | 2/11/19  | Communication                                    |                                            | -                       | Lab 4                  | [Wilke 24 (Image file formats for exporting)](https://serialmentor.com/dataviz/image-file-formats.html), [Wilke 26 (Telling a story)](https://serialmentor.com/dataviz/telling-a-story.html)                                                                                                     |
|    6b    | 2/13/19  | Choices and cycles                               |                                            | Homework 2              | -                      | [Healy 8 (Refine your plots)](https://socviz.co/refineplots.html#refineplots), [Wilke 17 (Redundant coding)](https://serialmentor.com/dataviz/redundant-coding.html), [Wilke 20 (Balance data-to-ink ratio)](https://serialmentor.com/dataviz/balance-data-ink.html)                             |
|    7a    | 2/18/19  | Visualizing uncertainty                          |                                            | -                       | -                      | [Wilke 16 (Visualizing Uncertainty)](https://serialmentor.com/dataviz/visualizing-uncertainty.html)                                                                                                                                                                                              |
|    7b    | 2/20/19  | Tables & fonts                                   |                                            | Lab 5                   | Homework 2             | [Healy 5 (Tables, labels, and notes)](https://socviz.co/workgeoms.html#workgeoms), [gt tables](https://gt.rstudio.com/articles/intro-creating-gt-tables.html)                                                                                                                                    |
|    8a    | 2/25/19  | Websites in R Markdown                           |                                            | -                       | Lab 5                  | [radix](https://rstudio.github.io/radix/), **Optional**: [RMD Sites](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html), [blogdown](https://bookdown.org/yihui/blogdown/)                                                                                                                 |
|    8b    | 2/27/19  | Dashboards                                       |                                            | Peer Review; Lab 6      | Portfolio Draft        | [RMD Dashboards](https://bookdown.org/yihui/rmarkdown/dashboards.html)                                                                                                                                                                                                                           |
|    9a    |  3/4/19  | Slides                                           |                                            | -                       | Lab 6                  | [Healy: Making Slides](https://kieranhealy.org/blog/archives/2018/03/24/making-slides/), [customization](https://github.com/yihui/xaringan/wiki)                                                                                                                                                 |
|    9b    |  3/6/19  | Work day                                         |                                            | -                       | Peer Review            | -                                                                                                                                                                                                                                                                                                |
|   10a    | 3/11/19  | Presentations                                    |                                            |                         | Presentation           | -                                                                                                                                                                                                                                                                                                |
|   10b    | 3/13/19  | Presentations                                    |                                            | -                       | Presentation           | -                                                                                                                                                                                                                                                                                                |
|    11    | 3/20/19  | Final Projects                                   |                                            |                         | Final Project          | -                                                                                                                                                                                                                                                                                                |